package com.mark.mail;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * auto generated by spring initializr (https://start.spring.io/)
 */
@SpringBootApplication
public class MailApplication {

	public static void main(String[] args) {
		SpringApplication.run(MailApplication.class, args);
	}

	@Bean
	public CommandLineRunner run(EmailService emailService) {
		return args -> {
			String sampleMessage = "Message Sample";
			emailService.sendEmail("mark-anthony.ortiz@roojai.com", "Email Subject Sample", sampleMessage);
		};
	}
}
